//note phrases
export const SET_NOTE_PHRASES = '[NOTE_PHRASES] SET_NOTE_PHRASES';
export const EDIT_NOTE_PHRASE = '[NOTE_PHRASES] EDIT_NOTE_PHRASE';
export const DELETE_NOTE_PHRASE = '[NOTE_PHRASES] DELETE_NOTE_PHRASE';
export const ADD_NOTE_PHRASE = '[NOTE_PHRASES] ADD_NOTE_PHRASE';
export const HIDE_SAVE_CANCEL_BTNS_NOTE_PHRASES =
	'[NOTE_PHRASES] HIDE_SAVE_CANCEL_BTNS_NOTE_PHRASES';
export const SHOW_SAVE_CANCEL_BTNS_NOTE_PHRASES =
	'[NOTE_PHRASES] SHOW_SAVE_CANCEL_BTNS_NOTE_PHRASES';

//email phrases
export const SET_EMAIL_PHRASES = '[EMAIL_PHRASES] SET_EMAIL_PHRASES';
export const EDIT_EMAIL_PHRASE = '[EMAIL_PHRASES] EDIT_EMAIL_PHRASE';
export const DELETE_EMAIL_PHRASE = '[EMAIL_PHRASES] DELETE_EMAIL_PHRASE';
export const ADD_EMAIL_PHRASE = '[EMAIL_PHRASES] ADD_EMAIL_PHRASE';
export const HIDE_SAVE_CANCEL_BTNS_EMAIL_PHRASES =
	'[EMAIL_PHRASES] HIDE_SAVE_CANCEL_BTNS_EMAIL_PHRASES';
export const SHOW_SAVE_CANCEL_BTNS_EMAIL_PHRASES =
	'[EMAIL_PHRASES] SHOW_SAVE_CANCEL_BTNS_EMAIL_PHRASES';
